### PR TITLE
Add PR number to the end of the line

### PR DESCRIPTION
**Pull request by dangoslen**

### CODE REVIEW

**Comment by vbrandl** [comment]
This looks like what I imagined.

It would be even better, if the line included the PR number in the form of a markdown link. So instead of `#123`, do `[#123](https://github.com/<owner>/<repo>/pull/123)`

**Comment by dangoslen** [comment]
I believe we are in luck there! GitHub [autolinks a lot of things](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls)  for us. Anything in the form of #<number> will link the issue or PR. As an example, #149 is an auto-link - I didn't have to form a full Markdown link for it to work

**Comment by vbrandl** [comment]
Last time I tested this, it didn't work it didn't work on the release page, but I just tested again and it did work. So that's fine.

**Comment by dangoslen** [comment]
Great. I'll merge this in and get a 3.1.0 release out shortly. I want to include some other dependency upgrades before that release though, but I should be able to get it out by today/tomorrow

**Comment by vbrandl** [comment]
Now I remembered, where autolinking didn't work. While it works fine in issues, PRs and on the release page, it does not work, when viewing the `CHANGELOG.md` file in the repository: https://github.com/dangoslen/dependabot-changelog-helper/blob/main/CHANGELOG.md

**Comment by dangoslen** [comment]
🤔 

I'm trying to weigh the pros and cons here. In one sense, I agree with you: it would be great for the changelog to have actual links rather than numbers. 

But on the other hand, formatting the link because a bit more difficult since we now need more context about the PR (which we do have available, the code just isn't reading it right now). 

If you want to implement it, I'll be happy to review it and make a release for it.

**Comment by dangoslen** [comment]
@vbrandl just following up here. Another consumer raised the same issue you did #188, so I ultimately added the PR context to be a full Markdown link in the end.

Thanks for the initial idea! I apologize it took another issue to get it to that final spot.

**Comment by vbrandl** [comment]
Cool stuff and no problem at all.
Thanks for the heads up

**Pull request merged**
