### PR TITLE
Small fixes for contributing guide

### PR DESCRIPTION
**Pull request by HonkingGoose**
## Changes:

- Capitalize proper noun TypeScript
- One sentence per line pattern
- End sentence with full stop `.`
- Simplify a sentence
- Fix newlines after header

## Context:

Small fixes to the contributing guide.

### CODE REVIEW

**Comment by dangoslen** [comment]
If you don't mind, I think I'll use this PR (since it's from a fork) to test some of the build changes I need to make, though it might make the PR rather noisy. 

If you aren't ok with that I'm happy to push this through too since it's just changing documentation.

**Comment by HonkingGoose** [comment]
Feel free to change things on my branch to get it working. 😉

**Comment by HonkingGoose** [comment]
The preview of Release Notes to be Created looks wrong, it shows the old release notes, but not the change I made in the file. This is probably a permissions problem:

```
 Pull request is not from a trusted source!
Error: Process completed with exit code 1.
```

**Comment by dangoslen** [comment]
Ah. So, since your fork doesn't contain the latest tag, the action thinks the release notes are for a not-yet-released change. That is why the preview notes showed up.

I think this is all good for now. I'll have to keep experimenting to find a way to compare tags across forks. I might just remove the functionality as the unslasph comment on PR action has been a bit buggy for me

**Pull request merged**
